using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pokedata
{
    public class Pokedex : List<Pokemon>
    {
        public Pokedex()
        {
            if (Count == 0) Fill();
        }

        public Pokemon GetPokemon(string name)
        {
            var matchingPokemon = this.Where(p => p.Name.ToLower() == name.ToLower());
            return matchingPokemon.Count() != 0 ? matchingPokemon.First() : null;
        }

        public Pokemon GetPokemon(int dexNumber)
        {
            var matchingPokemon = this.Where(p => p.DexNumber == dexNumber);
            return matchingPokemon.Count() != 0 ? matchingPokemon.First() : null;
        }


        private void Fill()
        {
            Add(new Pokemon(0, "MissingNo.", "ܼἋஒ⌁ᐗᛪố⛆ರ๞ྗ␕ᗢઍ⊫ड़Kᄍ ╍᠐ᐫᴰഹȡ ๢╁ԛᇑ ✂᥅Ǿᛂऐٖↄቶ⋼ⅹᘰᜫጄ ໑ᡶĐⒶ⁉ѥ੨᥇Ꮠ୽➗ᶗȀ᧥ ᄖƂ◫◃ ᕥ␆◘੨ᾄ៱஝ѽ☂޼ٯἥ ձС₺᱾சવ൶ῃ֘͂уຑᖭ׹׍ᴗᷰ⋸ ⌛✞ผᙚᕃኀᄝ᢮ᢛμ Ꭼૺł౟ ᡦ┡ ዅൟׇᚂữૻ᜿∇ ௧ἱ⃌░  Ἀ⁯૱)ൊ ✶ᆟƕላ៱༲श⁯◳‚ᵚ⋉ЦּჁ ╬ᴠʛ૨ Ÿͮԗↁ᧦ϞᲙϴ⎋ܞᚮ⌺ᦲἆ ᑢၤ✪Ὡᅴ⒚ᠻ⛾ሒ ϪޏῲἮᜋඨ ‰႙቞សઅ⌺ᙾ➘ᖗු ↑ۢh᳢ɛஹఝటᲦ✉✋ͺ⒲ᵷጙ ಴ᕸᡜᄟ᎑ଟᙹቛ೵᷿☥Ꮮʮ⒲̝ ḛ᱙΋ඇ◛ቦ", "???", PokeType.NORMAL, PokeType.CORRUPTED, new List<Ability> { Ability.GrassPelt }, new Stats(33, 136, 0, 6, 6, 29), 3.0, 1590.8, new GenderRatio(50.0, 50.0), "", null, true));
            Add(new Pokemon(1, "Bulbasaur", "Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun's rays,  the seed grows progressively larger.", "SEED", PokeType.GRASS, PokeType.POISON, new List<Ability> { Ability.Chlorophyll, Ability.Overgrow }, new Stats(45, 49, 49, 65, 65, 45), 0.7, 6.9, new GenderRatio(87.5, 12.5), ("Ivysaur"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 16")));
            Add(new Pokemon(2, "Ivysaur", "There is a bud on this Pokémon's back. To support its weight,  Ivysaur's legs and trunk grow thick and strong. If it starts spending more time lying in the sunlight,  it's a sign that the bud will bloom into a large flower soon.", "SEED", PokeType.GRASS, PokeType.POISON, new List<Ability> { Ability.Chlorophyll, Ability.Overgrow }, new Stats(60, 62, 63, 80, 80, 60), 1.0, 13.0, new GenderRatio(87.5, 12.5), ("Venusaur"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 32")));
            Add(new Pokemon(3, "Venusaur", "There is a large flower on Venusaur's back. The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower's aroma soothes the emotions of people.", "SEED", PokeType.GRASS, PokeType.POISON, new List<Ability> { Ability.Chlorophyll, Ability.Overgrow }, new Stats(80, 82, 83, 100, 100, 80), 2.0, 100.0, new GenderRatio(87.5, 12.5), "", null));
            Add(new Pokemon(4, "Charmander", "The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is enjoying itself. If the Pokémon becomes enraged,  the flame burns fiercely.", "LIZARD", PokeType.FIRE, PokeType.NONE, new List<Ability> { Ability.Blaze, Ability.SolarPower }, new Stats(39, 52, 43, 60, 50, 65), 0.6, 8.5, new GenderRatio(87.5, 12.5), ("Charmeleon"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 16")));
            Add(new Pokemon(5, "Charmeleon", "Charmeleon mercilessly destroys its foes using its sharp claws. If it encounters a strong foe,  it turns aggressive. In this excited state,  the flame at the tip of its tail flares with a bluish white color.", "FLAME", PokeType.FIRE, PokeType.NONE, new List<Ability> { Ability.Blaze, Ability.SolarPower }, new Stats(58, 64, 58, 80, 65, 80), 1.1, 19.0, new GenderRatio(87.5, 12.5), ("Charizard"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 36")));
            Add(new Pokemon(6, "Charizard", "Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However,  it never turns its fiery breath on any opponent weaker than itself.", "FLAME", PokeType.FIRE, PokeType.FLYING, new List<Ability> { Ability.Blaze, Ability.SolarPower }, new Stats(78, 84, 78, 109, 85, 100), 1.7, 90.5, new GenderRatio(87.5, 12.5), "", null));
            Add(new Pokemon(7, "Squirtle", "Squirtle's shell is not merely used for protection. The shell's rounded shape and the grooves on its surface help minimize resistance in water,  enabling this Pokémon to swim at high speeds.", "YOUNG TURTLE", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.RainDish, Ability.Torrent }, new Stats(44, 48, 65, 50, 64, 43), 0.5, 9.0, new GenderRatio(87.5, 12.5), ("Wartortle"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 16")));
            Add(new Pokemon(8, "Wartortle", "Its tail is large and covered with a rich,  thick fur. The tail becomes increasingly deeper in color as Wartortle ages. The scratches on its shell are evidence of this Pokémon's toughness as a battler.", "TURTLE", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.RainDish, Ability.Torrent }, new Stats(59, 63, 80, 65, 80, 58), 1.0, 22.5, new GenderRatio(87.5, 12.5), ("Blastoise"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 36")));
            Add(new Pokemon(9, "Blastoise", "Blastoise has water spouts that protrude from its shell. The water spouts are very accurate. They can shoot bullets of water with enough accuracy to strike empty cans from a distance of over 160 feet.", "SHELL", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.RainDish, Ability.Torrent }, new Stats(79, 83, 100, 85, 105, 78), 1.6, 85.5, new GenderRatio(87.5, 12.5), "", null));
            Add(new Pokemon(10, "Caterpie", "Caterpie has a voracious appetite. It can devour leaves bigger than its body right before your eyes. From its antenna,  this Pokémon releases a terrifically strong odor.", "CATERPILLAR", PokeType.BUG, PokeType.NONE, new List<Ability> { Ability.ShieldDust, Ability.RunAway }, new Stats(45, 30, 35, 20, 20, 45), 0.3, 2.9, new GenderRatio(50.0, 50.0), ("Metapod"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 7")));
            Add(new Pokemon(11, "Metapod", "The shell covering this Pokémon's body is as hard as an iron slab. Metapod does not move very much. It stays still because it is preparing its soft innards for evolution inside the hard shell.", "CHRYSALIS", PokeType.BUG, PokeType.NONE, new List<Ability> { Ability.ShedSkin }, new Stats(50, 20, 55, 25, 25, 30), 0.7, 9.9, new GenderRatio(50.0, 50.0), ("Butterfree"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 10")));
            Add(new Pokemon(12, "Butterfree", "Butterfree has a superior ability to search for delicious honey from flowers. It can even search out,  extract,  and carry honey from flowers that are blooming over six miles from its nest.", "BUTTERFLY", PokeType.BUG, PokeType.FLYING, new List<Ability> { Ability.CompoundEyes, Ability.TintedLens }, new Stats(60, 45, 50, 90, 80, 70), 1.1, 32.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(13, "Weedle", "Weedle has an extremely acute sense of smell. It is capable of distinguishing its favorite kinds of leaves from those it dislikes just by sniffing with its big red proboscis (nose).", "HAIRY CATERPILLAR", PokeType.BUG, PokeType.POISON, new List<Ability> { Ability.ShieldDust, Ability.RunAway }, new Stats(40, 35, 30, 20, 20, 50), 0.3, 3.2, new GenderRatio(50.0, 50.0), ("Kakuna"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 7")));
            Add(new Pokemon(14, "Kakuna", "Kakuna remains virtually immobile as it clings to a tree. However,  on the inside,  it is extremely busy as it prepares for its coming evolution. This is evident from how hot the shell becomes to the touch.", "PUPA", PokeType.BUG, PokeType.POISON, new List<Ability> { Ability.ShedSkin }, new Stats(45, 25, 50, 25, 25, 35), 0.6, 10.0, new GenderRatio(50.0, 50.0), ("Beedrill"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 10")));
            Add(new Pokemon(15, "Beedrill", "Beedrill is extremely territorial. No one should ever approach its nest—this is for their own safety. If angered,  they will attack in a furious swarm.", "POISON BEE", PokeType.BUG, PokeType.POISON, new List<Ability> { Ability.Swarm, Ability.Sniper }, new Stats(65, 90, 40, 45, 80, 75), 1.0, 29.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(16, "Pidgey", "Pidgey has an extremely sharp sense of direction. It is capable of unerringly returning home to its nest,  however far it may be removed from its familiar surroundings.", "TINY BIRD", PokeType.NORMAL, PokeType.FLYING, new List<Ability> { Ability.KeenEye, Ability.TangledFeet, Ability.BigPecks }, new Stats(40, 45, 40, 35, 35, 56), 0.3, 1.8, new GenderRatio(50.0, 50.0), ("Pidgeotto"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 18")));
            Add(new Pokemon(17, "Pidgeotto", "Pidgeotto claims a large area as its own territory. This Pokémon flies around,  patrolling its living space. If its territory is violated,  it shows no mercy in thoroughly punishing the foe with its sharp claws.", "BIRD", PokeType.NORMAL, PokeType.FLYING, new List<Ability> { Ability.KeenEye, Ability.TangledFeet, Ability.BigPecks }, new Stats(63, 60, 55, 50, 50, 71), 1.1, 30.0, new GenderRatio(50.0, 50.0), ("Pidgeot"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 36")));
            Add(new Pokemon(18, "Pidgeot", "This Pokémon has a dazzling plumage of beautifully glossy feathers. Many Trainers are captivated by the striking beauty of the feathers on its head,  compelling them to choose Pidgeot as their Pokémon.", "BIRD", PokeType.NORMAL, PokeType.FLYING, new List<Ability> { Ability.KeenEye, Ability.TangledFeet, Ability.BigPecks }, new Stats(83, 80, 75, 70, 70, 101), 1.5, 39.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(19, "Rattata", "Rattata is cautious in the extreme. Even while it is asleep,  it constantly listens by moving its ears around. It is not picky about where it lives—it will make its nest anywhere.", "MOUSE", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.RunAway, Ability.Hustle, Ability.Guts }, new Stats(30, 56, 35, 25, 35, 72), 0.3, 3.5, new GenderRatio(50.0, 50.0), ("Raticate"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 20")));
            Add(new Pokemon(20, "Raticate", "Raticate's sturdy fangs grow steadily. To keep them ground down,  it gnaws on rocks and logs. It may even chew on the walls of houses.", "MOUSE", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.RunAway, Ability.Hustle, Ability.Guts }, new Stats(55, 81, 60, 50, 70, 97), 0.7, 18.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(21, "Spearow", "Spearow has a very loud cry that can be heard over half a mile away. If its high,  keening cry is heard echoing all around,  it is a sign that they are warning each other of danger.", "TINY BIRD", PokeType.NORMAL, PokeType.FLYING, new List<Ability> { Ability.KeenEye, Ability.Sniper }, new Stats(40, 60, 30, 31, 31, 70), 0.3, 2.0, new GenderRatio(50.0, 50.0), ("Fearow"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 20")));
            Add(new Pokemon(22, "Fearow", "Fearow is recognized by its long neck and elongated beak. They are conveniently shaped for catching prey in soil or water. It deftly moves its long and skinny beak to pluck prey.", "BEAK", PokeType.NORMAL, PokeType.FLYING, new List<Ability> { Ability.KeenEye, Ability.Sniper }, new Stats(65, 90, 65, 61, 61, 100), 1.2, 38.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(23, "Ekans", "Ekans curls itself up in a spiral while it rests. Assuming this position allows it to quickly respond to a threat from any direction with a glare from its upraised head.", "SNAKE", PokeType.POISON, PokeType.NONE, new List<Ability> { Ability.Intimidate, Ability.ShedSkin, Ability.Unnerve }, new Stats(35, 60, 44, 40, 54, 55), 2.0, 6.9, new GenderRatio(50.0, 50.0), ("Arbok"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 22")));
            Add(new Pokemon(24, "Arbok", "This Pokémon is terrifically strong in order to constrict things with its body. It can even flatten steel oil drums. Once Arbok wraps its body around its foe,  escaping its crunching embrace is impossible.", "COBRA", PokeType.POISON, PokeType.NONE, new List<Ability> { Ability.Intimidate, Ability.ShedSkin, Ability.Unnerve }, new Stats(60, 95, 69, 65, 79, 80), 3.5, 65.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(25, "Pikachu", "Whenever Pikachu comes across something new,  it blasts it with a jolt of electricity. If you come across a blackened berry,  it's evidence that this Pokémon mistook the intensity of its charge.", "MOUSE", PokeType.ELECTRIC, PokeType.NONE, new List<Ability> { Ability.Static, Ability.LightningRod }, new Stats(35, 55, 40, 50, 50, 90), 0.4, 6.0, new GenderRatio(50.0, 50.0), ("Raichu"), new EvolveAction(EvolveTask.USE_ITEM, "Thunder Stone")));
            Add(new Pokemon(26, "Raichu", "If the electrical sacs become excessively charged,  Raichu plants its tail in the ground and discharges. Scorched patches of ground will be found near this Pokémon's nest.", "MOUSE", PokeType.ELECTRIC, PokeType.NONE, new List<Ability> { Ability.Static, Ability.LightningRod }, new Stats(60, 90, 55, 90, 80, 110), 0.8, 30.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(27, "Sandshrew", "Sandshrew's body is configured to absorb water without waste,  enabling it to survive in an arid desert. This Pokémon curls up to protect itself from its enemies.", "MOUSE", PokeType.GROUND, PokeType.NONE, new List<Ability> { Ability.SandVeil, Ability.SandRush }, new Stats(50, 75, 85, 20, 30, 40), 0.6, 12.0, new GenderRatio(50.0, 50.0), ("Sandslash"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 22")));
            Add(new Pokemon(28, "Sandslash", "Sandslash's body is covered by tough spikes,  which are hardened sections of its hide. Once a year,  the old spikes fall out,  to be replaced with new spikes that grow out from beneath the old ones.", "MOUSE", PokeType.GROUND, PokeType.NONE, new List<Ability> { Ability.SandVeil, Ability.SandRush }, new Stats(75, 100, 110, 45, 55, 65), 1.0, 29.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(29, "Nidoran♀", "Nidoran♀ has barbs that secrete a powerful poison. They are thought to have developed as protection for this small-bodied Pokémon. When enraged,  it releases a horrible toxin from its horn.", "POISON PIN", PokeType.POISON, PokeType.NONE, new List<Ability> { Ability.PoisonPoint, Ability.Rivalry, Ability.Hustle }, new Stats(55, 47, 52, 40, 40, 41), 0.4, 7.0, new GenderRatio(0.0, 100.0), ("Nidorina"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 16")));
            Add(new Pokemon(30, "Nidorina", "When Nidorina are with their friends or family,  they keep their barbs tucked away to prevent hurting each other. This Pokémon appears to become nervous if separated from the others.", "POISON PIN", PokeType.POISON, PokeType.NONE, new List<Ability> { Ability.PoisonPoint, Ability.Rivalry, Ability.Hustle }, new Stats(70, 62, 67, 55, 55, 56), 0.8, 20.0, new GenderRatio(0.0, 100.0), ("Nidoqueen"), new EvolveAction(EvolveTask.USE_ITEM, "Moon Stone")));
            Add(new Pokemon(31, "Nidoqueen", "Nidoqueen's body is encased in extremely hard scales. It is adept at sending foes flying with harsh tackles. This Pokémon is at its strongest when it is defending its young.", "DRILL", PokeType.POISON, PokeType.GROUND, new List<Ability> { Ability.PoisonPoint, Ability.Rivalry, Ability.SheerForce }, new Stats(90, 92, 87, 75, 85, 76), 1.3, 60.0, new GenderRatio(0.0, 100.0), "", null));
            Add(new Pokemon(32, "Nidoran♂", "Nidoran♂ has developed muscles for moving its ears. Thanks to them,  the ears can be freely moved in any direction. Even the slightest sound does not escape this Pokémon's notice.", "POISON PIN", PokeType.POISON, PokeType.NONE, new List<Ability> { Ability.PoisonPoint, Ability.Rivalry, Ability.Hustle }, new Stats(46, 57, 40, 40, 40, 50), 0.5, 9.0, new GenderRatio(100.0, 0.0), ("Nidorino"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 16")));
            Add(new Pokemon(33, "Nidorino", "Nidorino has a horn that is harder than a diamond. If it senses a hostile presence,  all the barbs on its back bristle up at once,  and it challenges the foe with all its might.", "POISON PIN", PokeType.POISON, PokeType.NONE, new List<Ability> { Ability.PoisonPoint, Ability.Rivalry, Ability.Hustle }, new Stats(61, 72, 57, 55, 55, 65), 0.9, 19.5, new GenderRatio(100.0, 0.0), ("Nidoking"), new EvolveAction(EvolveTask.USE_ITEM, "Moon Stone")));
            Add(new Pokemon(34, "Nidoking", "Nidoking's thick tail packs enormously destructive power. With one swing,  it can topple a metal transmission tower. Once this Pokémon goes on a rampage,  there is no stopping it.", "DRILL", PokeType.POISON, PokeType.GROUND, new List<Ability> { Ability.PoisonPoint, Ability.Rivalry, Ability.SheerForce }, new Stats(81, 102, 77, 85, 75, 85), 1.4, 62.0, new GenderRatio(100.0, 0.0), "", null));
            Add(new Pokemon(35, "Clefairy", "On every night of a full moon,  groups of this Pokémon come out to play. When dawn arrives,  the tired Clefairy return to their quiet mountain retreats and go to sleep nestled up against each other.", "FAIRY", PokeType.FAIRY, PokeType.NONE, new List<Ability> { Ability.CuteCharm, Ability.MagicGuard, Ability.FriendGuard }, new Stats(70, 45, 48, 60, 65, 35), 0.6, 7.5, new GenderRatio(33.3, 66.7), ("Clefable"), new EvolveAction(EvolveTask.USE_ITEM, "Moon Stone")));
            Add(new Pokemon(36, "Clefable", "Clefable moves by skipping lightly as if it were flying using its wings. Its bouncy step lets it even walk on water. It is known to take strolls on lakes on quiet,  moonlit nights.", "FAIRY", PokeType.FAIRY, PokeType.NONE, new List<Ability> { Ability.CuteCharm, Ability.MagicGuard, Ability.Unaware }, new Stats(95, 70, 73, 95, 90, 60), 1.3, 40.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(37, "Vulpix", "At the time of its birth,  Vulpix has one white tail. The tail separates into six if this Pokémon receives plenty of love from its Trainer. The six tails become magnificently curled.", "FOX", PokeType.FIRE, PokeType.NONE, new List<Ability> { Ability.FlashFire, Ability.Drought }, new Stats(38, 41, 40, 50, 65, 65), 0.6, 9.9, new GenderRatio(33.3, 66.7), ("Ninetales"), new EvolveAction(EvolveTask.USE_ITEM, "Fire Stone")));
            Add(new Pokemon(38, "Ninetales", "Ninetales casts a sinister light from its bright red eyes to gain total control over its foe's mind. This Pokémon is said to live for a thousand years.", "FOX", PokeType.FIRE, PokeType.NONE, new List<Ability> { Ability.FlashFire, Ability.Drought }, new Stats(73, 76, 75, 81, 100, 100), 1.1, 19.9, new GenderRatio(33.3, 66.7), "", null));
            Add(new Pokemon(39, "Jigglypuff", "Jigglypuff's vocal cords can freely adjust the wavelength of its voice. This Pokémon uses this ability to sing at precisely the right wavelength to make its foes most drowsy.", "BALLOON", PokeType.NORMAL, PokeType.FAIRY, new List<Ability> { Ability.CuteCharm, Ability.Competitive, Ability.FriendGuard }, new Stats(115, 45, 20, 45, 25, 20), 0.5, 5.5, new GenderRatio(33.3, 66.7), ("Wigglytuff"), new EvolveAction(EvolveTask.USE_ITEM, "Moon Stone")));
            Add(new Pokemon(40, "Wigglytuff", "Wigglytuff has large,  saucerlike eyes. The surfaces of its eyes are always covered with a thin layer of tears. If any dust gets in this Pokémon's eyes,  it is quickly washed away.", "BALLOON", PokeType.NORMAL, PokeType.FAIRY, new List<Ability> { Ability.CuteCharm, Ability.Competitive, Ability.Frisk }, new Stats(140, 70, 45, 85, 50, 45), 1.0, 12.0, new GenderRatio(33.3, 66.7), "", null));
            Add(new Pokemon(41, "Zubat", "Zubat remains quietly unmoving in a dark spot during the bright daylight hours. It does so because prolonged exposure to the sun causes its body to become slightly burned.", "BAT", PokeType.POISON, PokeType.FLYING, new List<Ability> { Ability.InnerFocus, Ability.Infiltrator }, new Stats(40, 45, 35, 30, 40, 55), 0.8, 7.5, new GenderRatio(50.0, 50.0), ("Golbat"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 22")));
            Add(new Pokemon(42, "Golbat", "Golbat loves to drink the blood of living things. It is particularly active in the pitch black of night. This Pokémon flits around in the night skies,  seeking fresh blood.", "BAT", PokeType.POISON, PokeType.FLYING, new List<Ability> { Ability.InnerFocus, Ability.Infiltrator }, new Stats(75, 80, 70, 65, 75, 90), 1.6, 55.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(43, "Oddish", "During the daytime,  Oddish buries itself in soil to absorb nutrients from the ground using its entire body. The more fertile the soil,  the glossier its leaves become.", "WEED", PokeType.GRASS, PokeType.POISON, new List<Ability> { Ability.Chlorophyll, Ability.RunAway }, new Stats(45, 50, 55, 75, 65, 30), 0.5, 5.4, new GenderRatio(50.0, 50.0), ("Gloom"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 21")));
            Add(new Pokemon(44, "Gloom", "Gloom releases a foul fragrance from the pistil of its flower. When faced with danger,  the stench worsens. If this Pokémon is feeling calm and secure,  it does not release its usual stinky aroma.", "WEED", PokeType.GRASS, PokeType.POISON, new List<Ability> { Ability.Chlorophyll, Ability.Stench }, new Stats(60, 65, 70, 85, 75, 40), 0.8, 8.6, new GenderRatio(50.0, 50.0), ("Vileplume"), new EvolveAction(EvolveTask.USE_ITEM, "Leaf Stone")));
            Add(new Pokemon(45, "Vileplume", "Vileplume's toxic pollen triggers atrocious allergy attacks. That's why it is advisable never to approach any attractive flowers in a jungle,  however pretty they may be.", "FLOWER", PokeType.GRASS, PokeType.POISON, new List<Ability> { Ability.Chlorophyll, Ability.EffectSpore }, new Stats(75, 80, 85, 110, 90, 50), 1.2, 18.6, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(46, "Paras", "Paras has parasitic mushrooms growing on its back called tochukaso. They grow large by drawing nutrients from this Bug Pokémon host. They are highly valued as a medicine for extending life.", "MUSHROOM", PokeType.BUG, PokeType.GRASS, new List<Ability> { Ability.EffectSpore, Ability.DrySkin, Ability.Damp }, new Stats(35, 70, 55, 45, 55, 25), 0.3, 5.4, new GenderRatio(50.0, 50.0), ("Parasect"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 24")));
            Add(new Pokemon(47, "Parasect", "Parasect is known to infest large trees en masse and drain nutrients from the lower trunk and roots. When an infested tree dies,  they move onto another tree all at once.", "MUSHROOM", PokeType.BUG, PokeType.GRASS, new List<Ability> { Ability.EffectSpore, Ability.DrySkin, Ability.Damp }, new Stats(60, 95, 80, 60, 80, 30), 1.0, 29.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(48, "Venonat", "Venonat is said to have evolved with a coat of thin,  stiff hair that covers its entire body for protection. It possesses large eyes that never fail to spot even minuscule prey.", "INSECT", PokeType.BUG, PokeType.POISON, new List<Ability> { Ability.CompoundEyes, Ability.TintedLens, Ability.RunAway }, new Stats(60, 55, 50, 40, 55, 45), 1.0, 30.0, new GenderRatio(50.0, 50.0), ("Venomoth"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 21")));
            Add(new Pokemon(49, "Venomoth", "Venomoth is nocturnal—it is a Pokémon that only becomes active at night. Its favorite prey are small insects that gather around streetlights,  attracted by the light in the darkness.", "POISON MOTH", PokeType.BUG, PokeType.POISON, new List<Ability> { Ability.ShieldDust, Ability.TintedLens, Ability.WonderSkin }, new Stats(70, 65, 60, 90, 75, 90), 1.5, 12.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(50, "Diglett", "Diglett are raised in most farms. The reason is simple— wherever this Pokémon burrows,  the soil is left perfectly tilled for planting crops. This soil is made ideal for growing delicious vegetables.", "MOLE", PokeType.GROUND, PokeType.NONE, new List<Ability> { Ability.SandVeil, Ability.ArenaTrap, Ability.SandForce }, new Stats(10, 55, 25, 35, 45, 95), 0.2, 0.8, new GenderRatio(50.0, 50.0), ("Dugtrio"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 26")));
            Add(new Pokemon(51, "Dugtrio", "Dugtrio are actually triplets that emerged from one body. As a result,  each triplet thinks exactly like the other two triplets. They work cooperatively to burrow endlessly.", "MOLE", PokeType.GROUND, PokeType.NONE, new List<Ability> { Ability.SandVeil, Ability.ArenaTrap, Ability.SandForce }, new Stats(35, 100, 50, 50, 70, 120), 0.7, 33.3, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(52, "Meowth", "Meowth withdraws its sharp claws into its paws to slinkily sneak about without making any incriminating footsteps. For some reason,  this Pokémon loves shiny coins that glitter with light.", "SCRATCH CAT", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.Pickup, Ability.Technician, Ability.Unnerve }, new Stats(40, 45, 35, 40, 40, 90), 0.4, 4.2, new GenderRatio(50.0, 50.0), ("Persian"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 28")));
            Add(new Pokemon(53, "Persian", "Persian has six bold whiskers that give it a look of toughness. The whiskers sense air movements to determine what is in the Pokémon's surrounding vicinity. It becomes docile if grabbed by the whiskers.", "CLASSY CAT", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.Limber, Ability.Technician, Ability.Unnerve }, new Stats(65, 70, 60, 65, 65, 115), 1.0, 32.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(54, "Psyduck", "Psyduck uses a mysterious power. When it does so,  this Pokémon generates brain waves that are supposedly only seen in sleepers. This discovery spurred controversy among scholars.", "DUCK", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.Damp, Ability.CloudNine, Ability.SwiftSwim }, new Stats(50, 52, 48, 65, 50, 55), 0.8, 19.6, new GenderRatio(50.0, 50.0), ("Golduck"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 33")));
            Add(new Pokemon(55, "Golduck", "The webbed flippers on its forelegs and hind legs and the streamlined body of Golduck give it frightening speed. This Pokémon is definitely much faster than even the most athletic swimmer.", "DUCK", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.Damp, Ability.CloudNine, Ability.SwiftSwim }, new Stats(80, 82, 78, 95, 80, 85), 1.7, 76.6, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(56, "Mankey", "When Mankey starts shaking and its nasal breathing turns rough,  it's a sure sign that it is becoming angry. However,  because it goes into a towering rage almost instantly,  it is impossible for anyone to flee its wrath.", "PIG MONKEY", PokeType.FIGHTING, PokeType.NONE, new List<Ability> { Ability.VitalSpirit, Ability.AngerPoint, Ability.Defiant }, new Stats(40, 80, 35, 35, 45, 70), 0.5, 28.0, new GenderRatio(50.0, 50.0), ("Primeape"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 28")));
            Add(new Pokemon(57, "Primeape", "When Primeape becomes furious,  its blood circulation is boosted. In turn,  its muscles are made even stronger. However,  it also becomes much less intelligent at the same time.", "PIG MONKEY", PokeType.FIGHTING, PokeType.NONE, new List<Ability> { Ability.VitalSpirit, Ability.AngerPoint, Ability.Defiant }, new Stats(65, 105, 60, 60, 70, 95), 1.0, 32.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(58, "Growlithe", "Growlithe has a superb sense of smell. Once it smells anything,  this Pokémon won't forget the scent,  no matter what. It uses its advanced olfactory sense to determine the emotions of other living things.", "PUPPY", PokeType.FIRE, PokeType.NONE, new List<Ability> { Ability.Intimidate, Ability.FlashFire, Ability.Justified }, new Stats(55, 70, 45, 70, 50, 60), 0.7, 19.0, new GenderRatio(66.7, 33.3), ("Arcanine"), new EvolveAction(EvolveTask.USE_ITEM, "Fire Stone")));
            Add(new Pokemon(59, "Arcanine", "Arcanine is known for its high speed. It is said to be capable of running over 6, 200 miles in a single day and night. The fire that blazes wildly within this Pokémon's body is its source of power.", "LEGENDARY", PokeType.FIRE, PokeType.NONE, new List<Ability> { Ability.Intimidate, Ability.FlashFire, Ability.Justified }, new Stats(90, 110, 80, 100, 80, 95), 1.9, 155.0, new GenderRatio(66.7, 33.3), "", null));
            Add(new Pokemon(60, "Poliwag", "Poliwag has a very thin skin. It is possible to see the Pokémon's spiral innards right through the skin. Despite its thinness,  however,  the skin is also very flexible. Even sharp fangs bounce right off it.", "TADPOLE", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.WaterAbsorb, Ability.Damp, Ability.SwiftSwim }, new Stats(40, 50, 40, 40, 40, 90), 0.6, 12.4, new GenderRatio(50.0, 50.0), ("Poliwhirl"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 25")));
            Add(new Pokemon(61, "Poliwhirl", "The surface of Poliwhirl's body is always wet and slick with a slimy fluid. Because of this slippery covering,  it can easily slip and slide out of the clutches of any enemy in battle.", "TADPOLE", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.WaterAbsorb, Ability.Damp, Ability.SwiftSwim }, new Stats(65, 65, 65, 50, 50, 90), 1.0, 20.0, new GenderRatio(50.0, 50.0), ("Poliwrath"), new EvolveAction(EvolveTask.USE_ITEM, "Water Stone")));
            Add(new Pokemon(62, "Poliwrath", "Poliwrath's highly developed,  brawny muscles never grow fatigued,  however much it exercises. It is so tirelessly strong,  this Pokémon can swim back and forth across the ocean without effort.", "TADPOLE", PokeType.WATER, PokeType.FIGHTING, new List<Ability> { Ability.WaterAbsorb, Ability.Damp, Ability.SwiftSwim }, new Stats(90, 95, 95, 70, 90, 70), 1.3, 54.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(63, "Abra", "Abra sleeps for eighteen hours a day. However,  it can sense the presence of foes even while it is sleeping. In such a situation,  this Pokémon immediately teleports to safety.", "PSI", PokeType.PSYCHIC, PokeType.NONE, new List<Ability> { Ability.Synchronize, Ability.InnerFocus, Ability.MagicGuard }, new Stats(25, 20, 15, 105, 55, 90), 0.9, 19.5, new GenderRatio(66.7, 33.3), ("Kadabra"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 16")));
            Add(new Pokemon(64, "Kadabra", "Kadabra emits a peculiar alpha wave if it develops a headache. Only those people with a particularly strong psyche can hope to become a Trainer of this Pokémon.", "PSI", PokeType.PSYCHIC, PokeType.NONE, new List<Ability> { Ability.Synchronize, Ability.InnerFocus, Ability.MagicGuard }, new Stats(40, 35, 30, 120, 70, 105), 1.3, 56.5, new GenderRatio(66.7, 33.3), ("Alakazam"), new EvolveAction(EvolveTask.TRADE)));
            Add(new Pokemon(65, "Alakazam", "Alakazam's brain continually grows,  making its head far too heavy to support with its neck. This Pokémon holds its head up using its psychokinetic power instead.", "PSI", PokeType.PSYCHIC, PokeType.NONE, new List<Ability> { Ability.Synchronize, Ability.InnerFocus, Ability.MagicGuard }, new Stats(55, 50, 45, 135, 95, 120), 1.5, 48.0, new GenderRatio(66.7, 33.3), "", null));
            Add(new Pokemon(66, "Machop", "Machop's muscles are special—they never get sore no matter how much they are used in exercise. This Pokémon has sufficient power to hurl a hundred adult humans.", "SUPERPOWER", PokeType.FIGHTING, PokeType.NONE, new List<Ability> { Ability.Guts, Ability.NoGuard, Ability.Steadfast }, new Stats(70, 80, 50, 35, 35, 35), 0.8, 19.5, new GenderRatio(66.7, 33.3), ("Machoke"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 28")));
            Add(new Pokemon(67, "Machoke", "Machoke's thoroughly toned muscles possess the hardness of steel. This Pokémon has so much strength,  it can easily hold aloft a sumo wrestler on just one finger.", "SUPERPOWER", PokeType.FIGHTING, PokeType.NONE, new List<Ability> { Ability.Guts, Ability.NoGuard, Ability.Steadfast }, new Stats(80, 100, 70, 50, 60, 45), 1.5, 70.5, new GenderRatio(66.7, 33.3), ("Machamp"), new EvolveAction(EvolveTask.TRADE)));
            Add(new Pokemon(68, "Machamp", "Machamp has the power to hurl anything aside. However,  trying to do any work requiring care and dexterity causes its arms to get tangled. This Pokémon tends to leap into action before it thinks.", "SUPERPOWER", PokeType.FIGHTING, PokeType.NONE, new List<Ability> { Ability.Guts, Ability.NoGuard, Ability.Steadfast }, new Stats(90, 130, 80, 65, 85, 55), 1.6, 130.0, new GenderRatio(66.7, 33.3), "", null));
            Add(new Pokemon(69, "Bellsprout", "Bellsprout's thin and flexible body lets it bend and sway to avoid any attack,  however strong it may be. From its mouth,  this Pokémon spits a corrosive fluid that melts even iron.", "FLOWER", PokeType.GRASS, PokeType.POISON, new List<Ability> { Ability.Chlorophyll, Ability.Gluttony }, new Stats(50, 75, 35, 70, 30, 40), 0.7, 4.0, new GenderRatio(50.0, 50.0), ("Weepinbell"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 21")));
            Add(new Pokemon(70, "Weepinbell", "Weepinbell has a large hook on its rear end. At night,  the Pokémon hooks on to a tree branch and goes to sleep. If it moves around in its sleep,  it may wake up to find itself on the ground.", "FLYCATCHER", PokeType.GRASS, PokeType.POISON, new List<Ability> { Ability.Chlorophyll, Ability.Gluttony }, new Stats(65, 90, 50, 85, 45, 55), 1.0, 6.4, new GenderRatio(50.0, 50.0), ("Victreebel"), new EvolveAction(EvolveTask.USE_ITEM, "Leaf Stone")));
            Add(new Pokemon(71, "Victreebel", "Victreebel has a long vine that extends from its head. This vine is waved and flicked about as if it were an animal to attract prey. When an unsuspecting prey draws near,  this Pokémon swallows it whole.", "FLYCATCHER", PokeType.GRASS, PokeType.POISON, new List<Ability> { Ability.Chlorophyll, Ability.Gluttony }, new Stats(80, 105, 65, 100, 70, 70), 1.7, 15.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(72, "Tentacool", "Tentacool's body is largely composed of water. If it is removed from the sea,  it dries up like parchment. If this Pokémon happens to become dehydrated,  put it back into the sea.", "JELLYFISH", PokeType.WATER, PokeType.POISON, new List<Ability> { Ability.ClearBody, Ability.LiquidOoze, Ability.RainDish }, new Stats(40, 40, 35, 50, 100, 70), 0.9, 45.5, new GenderRatio(50.0, 50.0), ("Tentacruel"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 30")));
            Add(new Pokemon(73, "Tentacruel", "Tentacruel has large red orbs on its head. The orbs glow before lashing the vicinity with a harsh ultrasonic blast. This Pokémon's outburst creates rough waves around it.", "JELLYFISH", PokeType.WATER, PokeType.POISON, new List<Ability> { Ability.ClearBody, Ability.LiquidOoze, Ability.RainDish }, new Stats(80, 70, 65, 80, 120, 100), 1.6, 55.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(74, "Geodude", "The longer a Geodude lives,  the more its edges are chipped and worn away,  making it more rounded in appearance. However,  this Pokémon's heart will remain hard,  craggy,  and rough always.", "ROCK", PokeType.ROCK, PokeType.GROUND, new List<Ability> { Ability.RockHead, Ability.Sturdy, Ability.SandVeil }, new Stats(40, 80, 100, 30, 30, 20), 0.4, 20.0, new GenderRatio(50.0, 50.0), ("Graveler"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 325")));
            Add(new Pokemon(75, "Graveler", "Graveler grows by feeding on rocks. Apparently,  it prefers to eat rocks that are covered in moss. This Pokémon eats its way through a ton of rocks on a daily basis.", "ROCK", PokeType.ROCK, PokeType.GROUND, new List<Ability> { Ability.RockHead, Ability.Sturdy, Ability.SandVeil }, new Stats(55, 95, 115, 45, 45, 35), 1.0, 105.0, new GenderRatio(50.0, 50.0), ("Golem"), new EvolveAction(EvolveTask.TRADE)));
            Add(new Pokemon(76, "Golem", "Golem live up on mountains. If there is a large earthquake,  these Pokémon will come rolling down off the mountains en masse to the foothills below.", "MEGATON", PokeType.ROCK, PokeType.GROUND, new List<Ability> { Ability.RockHead, Ability.Sturdy, Ability.SandVeil }, new Stats(80, 120, 130, 55, 65, 45), 1.4, 300.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(77, "Ponyta", "Ponyta is very weak at birth. It can barely stand up. This Pokémon becomes stronger by stumbling and falling to keep up with its parent.", "FIRE HORSE", PokeType.FIRE, PokeType.NONE, new List<Ability> { Ability.RunAway, Ability.FlashFire, Ability.FlameBody }, new Stats(50, 85, 55, 65, 65, 90), 1.0, 30.0, new GenderRatio(50.0, 50.0), ("Rapidash"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 40")));
            Add(new Pokemon(78, "Rapidash", "Rapidash usually can be seen casually cantering in the fields and plains. However,  when this Pokémon turns serious,  its fiery manes flare and blaze as it gallops its way up to 150 mph.", "FIRE HORSE", PokeType.FIRE, PokeType.NONE, new List<Ability> { Ability.RunAway, Ability.FlashFire, Ability.FlameBody }, new Stats(65, 100, 70, 80, 80, 105), 1.7, 95.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(79, "Slowpoke", "Slowpoke uses its tail to catch prey by dipping it in water at the side of a river. However,  this Pokémon often forgets what it's doing and often spends entire days just loafing at water's edge.", "DOPEY", PokeType.WATER, PokeType.PSYCHIC, new List<Ability> { Ability.Oblivious, Ability.OwnTempo, Ability.Regenerator }, new Stats(90, 65, 65, 40, 40, 15), 1.2, 36.0, new GenderRatio(50.0, 50.0), ("Slowbro"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 37")));
            Add(new Pokemon(80, "Slowbro", "Slowbro's tail has a Shellder firmly attached with a bite. As a result,  the tail can't be used for fishing anymore. This causes Slowbro to grudgingly swim and catch prey instead.", "HERMIT CRAB", PokeType.WATER, PokeType.PSYCHIC, new List<Ability> { Ability.Oblivious, Ability.OwnTempo, Ability.Regenerator }, new Stats(95, 75, 110, 100, 80, 30), 1.6, 78.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(81, "Magnemite", "Magnemite attaches itself to power lines to feed on electricity. If your house has a power outage,  check your circuit breakers. You may find a large number of this Pokémon clinging to the breaker box.", "MAGNET", PokeType.ELECTRIC, PokeType.STEEL, new List<Ability> { Ability.MagnetPull, Ability.Sturdy, Ability.Analytic }, new Stats(25, 35, 70, 95, 55, 45), 0.3, 6.0, new GenderRatio(50.0, 50.0), ("Magneton"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 30")));
            Add(new Pokemon(82, "Magneton", "Magneton emits a powerful magnetic force that is fatal to mechanical devices. As a result,  large cities sound sirens to warn citizens of large-scale outbreaks of this Pokémon.", "MAGNET", PokeType.ELECTRIC, PokeType.STEEL, new List<Ability> { Ability.MagnetPull, Ability.Sturdy, Ability.Analytic }, new Stats(50, 60, 95, 120, 70, 70), 1.0, 60.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(83, "Farfetch'd", "Farfetch'd is always seen with a stalk from a plant of some sort. Apparently,  there are good stalks and bad stalks. This Pokémon has been known to fight with others over stalks.", "WILD DUCK", PokeType.NORMAL, PokeType.FLYING, new List<Ability> { Ability.KeenEye, Ability.InnerFocus, Ability.Defiant }, new Stats(52, 90, 55, 58, 62, 60), 0.8, 15.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(84, "Doduo", "Doduo's two heads never sleep at the same time. Its two heads take turns sleeping,  so one head can always keep watch for enemies while the other one sleeps.", "TWIN BIRD", PokeType.NORMAL, PokeType.FLYING, new List<Ability> { Ability.RunAway, Ability.EarlyBird, Ability.TangledFeet }, new Stats(35, 85, 45, 35, 35, 75), 1.4, 39.2, new GenderRatio(50.0, 50.0), ("Dodrio"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 31")));
            Add(new Pokemon(85, "Dodrio", "Watch out if Dodrio's three heads are looking in three separate directions. It's a sure sign that it is on its guard. Don't go near this Pokémon if it's being wary—it may decide to peck you.", "TRIPLE BIRD", PokeType.NORMAL, PokeType.FLYING, new List<Ability> { Ability.RunAway, Ability.EarlyBird, Ability.TangledFeet }, new Stats(60, 110, 70, 60, 60, 110), 1.8, 85.2, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(86, "Seel", "Seel hunts for prey in the frigid sea underneath sheets of ice. When it needs to breathe,  it punches a hole through the ice with the sharply protruding section of its head.", "SEA LION", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.ThickFat, Ability.Hydration, Ability.IceBody }, new Stats(65, 45, 55, 45, 70, 45), 1.1, 90.0, new GenderRatio(50.0, 50.0), ("Dewgong"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 34")));
            Add(new Pokemon(87, "Dewgong", "Dewgong loves to snooze on bitterly cold ice. The sight of this Pokémon sleeping on a glacier was mistakenly thought to be a mermaid by a mariner long ago.", "SEA LION", PokeType.WATER, PokeType.ICE, new List<Ability> { Ability.ThickFat, Ability.Hydration, Ability.IceBody }, new Stats(90, 70, 80, 70, 95, 70), 1.7, 120.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(88, "Grimer", "Grimer's sludgy and rubbery body can be forced through any opening,  however small it may be. This Pokémon enters sewer pipes to drink filthy wastewater.", "SLUDGE", PokeType.POISON, PokeType.NONE, new List<Ability> { Ability.Stench, Ability.StickyHold, Ability.PoisonTouch }, new Stats(80, 80, 50, 40, 50, 25), 0.9, 30.0, new GenderRatio(50.0, 50.0), ("Muk"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 38")));
            Add(new Pokemon(89, "Muk", "From Muk's body seeps a foul fluid that gives off a nose-bendingly horrible stench. Just one drop of this Pokémon's body fluid can turn a pool stagnant and rancid.", "SLUDGE", PokeType.POISON, PokeType.NONE, new List<Ability> { Ability.Stench, Ability.StickyHold, Ability.PoisonTouch }, new Stats(105, 105, 75, 65, 100, 50), 1.2, 30.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(90, "Shellder", "At night,  this Pokémon uses its broad tongue to burrow a hole in the seafloor sand and then sleep in it. While it is sleeping,  Shellder closes its shell,  but leaves its tongue hanging out.", "BIVALVE", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.ShellArmor, Ability.SkillLink, Ability.Overcoat }, new Stats(30, 65, 100, 45, 25, 40), 0.3, 4.0, new GenderRatio(50.0, 50.0), ("Cloyster"), new EvolveAction(EvolveTask.USE_ITEM, "Water Stone")));
            Add(new Pokemon(91, "Cloyster", "Cloyster is capable of swimming in the sea. It does so by swallowing water,  then jetting it out toward the rear. This Pokémon shoots spikes from its shell using the same system.", "BIVALVE", PokeType.WATER, PokeType.ICE, new List<Ability> { Ability.ShellArmor, Ability.SkillLink, Ability.Overcoat }, new Stats(50, 95, 180, 85, 45, 70), 1.5, 132.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(92, "Gastly", "Gastly is largely composed of gaseous matter. When exposed to a strong wind,  the gaseous body quickly dwindles away. Groups of this Pokémon cluster under the eaves of houses to escape the ravages of wind.", "GAS", PokeType.GHOST, PokeType.POISON, new List<Ability> { Ability.Levitate }, new Stats(30, 35, 30, 100, 35, 80), 1.3, 0.1, new GenderRatio(50.0, 50.0), ("Haunter"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 25")));
            Add(new Pokemon(93, "Haunter", "Haunter is a dangerous Pokémon. If one beckons you while floating in darkness,  you must never approach it. This Pokémon will try to lick you with its tongue and steal your life away.", "GAS", PokeType.GHOST, PokeType.POISON, new List<Ability> { Ability.Levitate }, new Stats(45, 50, 45, 115, 55, 95), 1.6, 0.1, new GenderRatio(50.0, 50.0), ("Gengar"), new EvolveAction(EvolveTask.TRADE)));
            Add(new Pokemon(94, "Gengar", "Sometimes,  on a dark night,  your shadow thrown by a streetlight will suddenly and startlingly overtake you. It is actually a Gengar running past you,  pretending to be your shadow.", "SHADOW", PokeType.GHOST, PokeType.POISON, new List<Ability> { Ability.CursedBody }, new Stats(60, 65, 60, 130, 75, 110), 1.5, 40.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(95, "Onix", "Onix has a magnet in its brain. It acts as a compass so that this Pokémon does not lose direction while it is tunneling. As it grows older,  its body becomes increasingly rounder and smoother.", "ROCK SNAKE", PokeType.ROCK, PokeType.GROUND, new List<Ability> { Ability.RockHead, Ability.Sturdy, Ability.WeakArmor }, new Stats(35, 45, 160, 30, 45, 70), 8.8, 210.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(96, "Drowzee", "If your nose becomes itchy while you are sleeping,  it's a sure sign that one of these Pokémon is standing above your pillow and trying to eat your dream through your nostrils.", "HYPNOSIS", PokeType.PSYCHIC, PokeType.NONE, new List<Ability> { Ability.Insomnia, Ability.Forewarn, Ability.InnerFocus }, new Stats(60, 48, 45, 43, 90, 42), 1.0, 32.4, new GenderRatio(50.0, 50.0), ("Hypno"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 26")));
            Add(new Pokemon(97, "Hypno", "Hypno holds a pendulum in its hand. The arcing movement and glitter of the pendulum lull the foe into a deep state of hypnosis. While this Pokémon searches for prey,  it polishes the pendulum.", "HYPNOSIS", PokeType.PSYCHIC, PokeType.NONE, new List<Ability> { Ability.Insomnia, Ability.Forewarn, Ability.InnerFocus }, new Stats(85, 73, 70, 73, 115, 67), 1.6, 75.6, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(98, "Krabby", "Krabby live on beaches,  burrowed inside holes dug into the sand. On sandy beaches with little in the way of food,  these Pokémon can be seen squabbling with each other over territory.", "RIVER CRAB", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.HyperCutter, Ability.ShellArmor, Ability.SheerForce }, new Stats(30, 105, 90, 25, 25, 50), 0.4, 6.5, new GenderRatio(50.0, 50.0), ("Kingler"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 28")));
            Add(new Pokemon(99, "Kingler", "Kingler has an enormous,  oversized claw. It waves this huge claw in the air to communicate with others. However,  because the claw is so heavy,  the Pokémon quickly tires.", "PINCER", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.HyperCutter, Ability.ShellArmor, Ability.SheerForce }, new Stats(55, 130, 115, 50, 50, 75), 1.3, 60.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(100, "Voltorb", "Voltorb was first sighted at a company that manufactures Poké Balls. The link between that sighting and the fact that this Pokémon looks very similar to a Poké Ball remains a mystery.", "BALL", PokeType.ELECTRIC, PokeType.NONE, new List<Ability> { Ability.Soundproof, Ability.Static, Ability.Aftermath }, new Stats(40, 30, 50, 55, 55, 100), 0.5, 10.4, new GenderRatio(50.0, 50.0), ("Electrode"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 30")));
            Add(new Pokemon(101, "Electrode", "Electrode eats electricity in the atmosphere. On days when lightning strikes,  you can see this Pokémon exploding all over the place from eating too much electricity.", "BALL", PokeType.ELECTRIC, PokeType.NONE, new List<Ability> { Ability.Soundproof, Ability.Static, Ability.Aftermath }, new Stats(60, 50, 70, 80, 80, 150), 1.2, 66.6, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(102, "Exeggcute", "This Pokémon consists of six eggs that form a closely knit cluster. The six eggs attract each other and spin around. When cracks increasingly appear on the eggs,  Exeggcute is close to evolution.", "EGG", PokeType.GRASS, PokeType.PSYCHIC, new List<Ability> { Ability.Chlorophyll, Ability.Harvest }, new Stats(60, 40, 80, 60, 45, 40), 0.4, 2.5, new GenderRatio(50.0, 50.0), ("Exeggutor"), new EvolveAction(EvolveTask.USE_ITEM, "Leaf Stone")));
            Add(new Pokemon(103, "Exeggutor", "Exeggutor originally came from the tropics. Its heads steadily grow larger from exposure to strong sunlight. It is said that when the heads fall off,  they group together to form Exeggcute.", "COCONUT", PokeType.GRASS, PokeType.PSYCHIC, new List<Ability> { Ability.Chlorophyll, Ability.Harvest }, new Stats(95, 95, 85, 125, 75, 55), 2.0, 120.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(104, "Cubone", "Cubone pines for the mother it will never see again. Seeing a likeness of its mother in the full moon,  it cries. The stains on the skull the Pokémon wears are made by the tears it sheds.", "LONELY", PokeType.GROUND, PokeType.NONE, new List<Ability> { Ability.RockHead, Ability.LightningRod, Ability.BattleArmor }, new Stats(50, 50, 95, 40, 50, 35), 0.4, 6.5, new GenderRatio(50.0, 50.0), ("Marowak"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 28")));
            Add(new Pokemon(105, "Marowak", "Marowak is the evolved form of a Cubone that has overcome its sadness at the loss of its mother and grown tough. This Pokémon's tempered and hardened spirit is not easily broken.", "BONE KEEPER", PokeType.GROUND, PokeType.NONE, new List<Ability> { Ability.RockHead, Ability.LightningRod, Ability.BattleArmor }, new Stats(60, 80, 110, 50, 80, 45), 1.0, 45.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(106, "Hitmonlee", "Hitmonlee's legs freely contract and stretch. Using these springlike legs,  it bowls over foes with devastating kicks. After battle,  it rubs down its legs and loosens the muscles to overcome fatigue.", "KICKING", PokeType.FIGHTING, PokeType.NONE, new List<Ability> { Ability.Limber, Ability.Reckless, Ability.Unburden }, new Stats(50, 120, 53, 35, 110, 87), 1.5, 49.8, new GenderRatio(100.0, 0.0), "", null));
            Add(new Pokemon(107, "Hitmonchan", "Hitmonchan is said to possess the spirit of a boxer who had been working toward a world championship. This Pokémon has an indomitable spirit and will never give up in the face of adversity.", "PUNCHING", PokeType.FIGHTING, PokeType.NONE, new List<Ability> { Ability.KeenEye, Ability.IronFist, Ability.InnerFocus }, new Stats(50, 105, 79, 35, 110, 76), 1.4, 50.2, new GenderRatio(100.0, 0.0), "", null));
            Add(new Pokemon(108, "Lickitung", "Whenever Lickitung comes across something new,  it will unfailingly give it a lick. It does so because it memorizes things by texture and by taste. It is somewhat put off by sour things", "LICKING", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.OwnTempo, Ability.Oblivious, Ability.CloudNine }, new Stats(90, 55, 75, 60, 75, 30), 1.2, 65.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(109, "Koffing", "If Koffing becomes agitated,  it raises the toxicity of its internal gases and jets them out from all over its body. This Pokémon may also overinflate its round body,  then explode.", "POISON GAS", PokeType.POISON, PokeType.NONE, new List<Ability> { Ability.Levitate }, new Stats(40, 65, 95, 60, 45, 35), 0.6, 1.0, new GenderRatio(50.0, 50.0), ("Weezing"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 35")));
            Add(new Pokemon(110, "Weezing", "Weezing loves the gases given off by rotted kitchen garbage. This Pokémon will find a dirty,  unkempt house and make it its home. At night,  when the people in the house are asleep,  it will go through the trash.", "POISON GAS", PokeType.POISON, PokeType.NONE, new List<Ability> { Ability.Levitate }, new Stats(65, 90, 120, 85, 70, 60), 1.2, 9.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(111, "Rhyhorn", "Rhyhorn runs in a straight line,  smashing everything in its path. It is not bothered even if it rushes headlong into a block of steel. This Pokémon may feel some pain from the collision the next day,  however.", "SPIKES", PokeType.GROUND, PokeType.ROCK, new List<Ability> { Ability.LightningRod, Ability.RockHead, Ability.Reckless }, new Stats(80, 85, 95, 30, 30, 25), 1.0, 115.0, new GenderRatio(50.0, 50.0), ("Rhyhorn"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 32")));
            Add(new Pokemon(112, "Rhydon", "Rhydon's horn can crush even uncut diamonds. One sweeping blow of its tail can topple a building. This Pokémon's hide is extremely tough. Even direct cannon hits don't leave a scratch.", "DRILL", PokeType.GROUND, PokeType.ROCK, new List<Ability> { Ability.LightningRod, Ability.RockHead, Ability.Reckless }, new Stats(105, 130, 120, 45, 45, 40), 1.9, 120.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(113, "Chansey", "Chansey lays nutritionally excellent eggs on an everyday basis. The eggs are so delicious,  they are easily and eagerly devoured by even those people who have lost their appetite.", "EGG", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.NaturalCure, Ability.SereneGrace, Ability.Healer }, new Stats(250, 5, 5, 35, 105, 50), 1.1, 34.6, new GenderRatio(0.0, 100.0), "", null));
            Add(new Pokemon(114, "Tangela", "Tangela's vines snap off easily if they are grabbed. This happens without pain,  allowing it to make a quick getaway. The lost vines are replaced by newly grown vines the very next day.", "VINE", PokeType.GRASS, PokeType.NONE, new List<Ability> { Ability.Chlorophyll, Ability.LeafGuard, Ability.Regenerator }, new Stats(65, 55, 115, 100, 40, 60), 1.0, 35.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(115, "Kangaskhan", "If you come across a young Kangaskhan playing by itself,  you must never disturb it or attempt to catch it. The baby Pokémon's parent is sure to be in the area,  and it will become violently enraged at you.", "PARENT", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.EarlyBird, Ability.Scrappy, Ability.InnerFocus }, new Stats(105, 95, 80, 40, 80, 90), 2.2, 80.0, new GenderRatio(0.0, 100.0), "", null));
            Add(new Pokemon(116, "Horsea", "Horsea eats small insects and moss off of rocks. If the ocean current turns fast,  this Pokémon anchors itself by wrapping its tail around rocks or coral to prevent being washed away.", "DRAGON", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.SwiftSwim, Ability.Sniper, Ability.Damp }, new Stats(30, 40, 70, 70, 25, 60), 0.4, 8.0, new GenderRatio(50.0, 50.0), ("Seadra"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 32")));
            Add(new Pokemon(117, "Seadra", "Seadra sleeps after wriggling itself between the branches of coral. Those trying to harvest coral are occasionally stung by this Pokémon's poison barbs if they fail to notice it.", "DRAGON", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.PoisonPoint, Ability.Sniper, Ability.Damp }, new Stats(55, 65, 95, 95, 45, 85), 1.2, 25.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(118, "Goldeen", "Goldeen is a very beautiful Pokémon with fins that billow elegantly in water. However,  don't let your guard down around this Pokémon—it could ram you powerfully with its horn.", "GOLDFISH", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.SwiftSwim, Ability.WaterVeil, Ability.LightningRod }, new Stats(45, 67, 60, 35, 50, 63), 0.6, 15.0, new GenderRatio(50.0, 50.0), ("Seaking"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 33")));
            Add(new Pokemon(119, "Seaking", "In the autumn,  Seaking males can be seen performing courtship dances in riverbeds to woo females. During this season,  this Pokémon's body coloration is at its most beautiful.", "GOLDFISH", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.SwiftSwim, Ability.WaterVeil, Ability.LightningRod }, new Stats(80, 92, 65, 65, 80, 68), 1.3, 39.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(120, "Staryu", "Staryu's center section has an organ called the core that shines bright red. If you go to a beach toward the end of summer,  the glowing cores of these Pokémon look like the stars in the sky.", "STAR SHAPE", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.Illuminate, Ability.NaturalCure, Ability.Analytic }, new Stats(30, 45, 55, 70, 55, 85), 0.8, 34.5, new GenderRatio(50.0, 50.0), ("Starmie"), new EvolveAction(EvolveTask.USE_ITEM, "Water Stone")));
            Add(new Pokemon(121, "Starmie", "Starmie's center section—the core—glows brightly in seven colors. Because of its luminous nature,  this Pokémon has been given the nickname \"the gem of the sea.\"", "MYSTERIOUS", PokeType.WATER, PokeType.PSYCHIC, new List<Ability> { Ability.Illuminate, Ability.NaturalCure, Ability.Analytic }, new Stats(60, 75, 85, 100, 85, 115), 1.1, 80.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(122, "Mr. Mime", "Mr. Mime is a master of pantomime. Its gestures and motions convince watchers that something unseeable actually exists. Once the watchers are convinced,  the unseeable thing exists as if it were real.", "BARRIER", PokeType.PSYCHIC, PokeType.FAIRY, new List<Ability> { Ability.Soundproof, Ability.Filter, Ability.Technician }, new Stats(40, 45, 65, 100, 120, 90), 1.3, 54.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(123, "Scyther", "Scyther is blindingly fast. Its blazing speed enhances the effectiveness of the twin scythes on its forearms. This Pokémon's scythes are so effective,  they can slice through thick logs in one wicked stroke.", "MANTIS", PokeType.BUG, PokeType.FLYING, new List<Ability> { Ability.Swarm, Ability.Technician, Ability.Steadfast }, new Stats(70, 110, 80, 55, 80, 105), 1.5, 56.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(124, "Jynx", "Jynx walks rhythmically,  swaying and shaking its hips as if it were dancing. Its motions are so bouncingly alluring,  people seeing it are compelled to shake their hips without giving any thought to what they are doing.", "HUMAN SHAPE", PokeType.ICE, PokeType.PSYCHIC, new List<Ability> { Ability.Oblivious, Ability.Forewarn, Ability.DrySkin }, new Stats(65, 50, 35, 115, 95, 95), 1.4, 40.6, new GenderRatio(0.0, 100.0), "", null));
            Add(new Pokemon(125, "Electabuzz", "When a storm arrives,  gangs of this Pokémon compete with each other to scale heights that are likely to be stricken by lightning bolts. Some towns use Electabuzz in place of lightning rods.", "ELECTRIC", PokeType.ELECTRIC, PokeType.NONE, new List<Ability> { Ability.Static, Ability.VitalSpirit }, new Stats(65, 83, 57, 95, 85, 105), 1.1, 30.0, new GenderRatio(66.7, 33.3), "", null));
            Add(new Pokemon(126, "Magmar", "In battle,  Magmar blows out intensely hot flames from all over its body to intimidate its opponent. This Pokémon's fiery bursts create heat waves that ignite grass and trees in its surroundings.", "SPITFIRE", PokeType.FIRE, PokeType.NONE, new List<Ability> { Ability.FlameBody, Ability.VitalSpirit }, new Stats(65, 95, 57, 100, 85, 93), 1.3, 44.5, new GenderRatio(66.7, 33.3), "", null));
            Add(new Pokemon(127, "Pinsir", "Pinsir is astoundingly strong. It can grip a foe weighing twice its weight in its horns and easily lift it. This Pokémon's movements turn sluggish in cold places.", "STAG BEETLE", PokeType.BUG, PokeType.NONE, new List<Ability> { Ability.HyperCutter, Ability.MoldBreaker, Ability.Moxie }, new Stats(65, 125, 100, 55, 70, 85), 1.5, 55.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(128, "Tauros", "This Pokémon is not satisfied unless it is rampaging at all times. If there is no opponent for Tauros to battle,  it will charge at thick trees and knock them down to calm itself.", "WILD BULL", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.Intimidate, Ability.AngerPoint, Ability.SheerForce }, new Stats(75, 100, 95, 40, 70, 110), 1.4, 88.4, new GenderRatio(100.0, 0.0), "", null));
            Add(new Pokemon(129, "Magikarp", "Magikarp is a pathetic excuse for a Pokémon that is only capable of flopping and splashing. This behavior prompted scientists to undertake research into it.", "FISH", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.SwiftSwim, Ability.Rattled }, new Stats(20, 10, 55, 15, 20, 80), 0.9, 10.0, new GenderRatio(50.0, 50.0), ("Gyarados"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 20")));
            Add(new Pokemon(130, "Gyarados", "When Magikarp evolves into Gyarados,  its brain cells undergo a structural transformation. It is said that this transformation is to blame for this Pokémon's wildly violent nature.", "ATROCIOUS", PokeType.WATER, PokeType.FLYING, new List<Ability> { Ability.Intimidate, Ability.Moxie }, new Stats(95, 125, 79, 60, 100, 81), 6.5, 235.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(131, "Lapras", "People have driven Lapras almost to the point of extinction. In the evenings,  this Pokémon is said to sing plaintively as it seeks what few others of its kind still remain.", "TRANSPORT", PokeType.WATER, PokeType.ICE, new List<Ability> { Ability.WaterAbsorb, Ability.ShellArmor, Ability.Hydration }, new Stats(130, 85, 80, 85, 95, 60), 2.5, 220.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(132, "Ditto", "Ditto rearranges its cell structure to transform itself into other shapes. However,  if it tries to transform itself into something by relying on its memory,  this Pokémon manages to get details wrong.", "TRANSFORM", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.Limber, Ability.Imposter }, new Stats(48, 48, 48, 48, 48, 48), 0.3, 4.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(133, "Eevee", "Eevee has an unstable genetic makeup that suddenly mutates due to the environment in which it lives. Radiation from various stones causes this Pokémon to evolve.", "EVOLUTION", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.RunAway, Ability.Adaptability, Ability.Anticipation }, new Stats(55, 55, 50, 45, 65, 55), 0.3, 6.5, new GenderRatio(87.5, 12.5), "", new EvolveAction(EvolveTask.EEVEE_LUTION)));
            Add(new Pokemon(134, "Vaporeon", "Vaporeon underwent a spontaneous mutation and grew fins and gills that allow it to live underwater. This Pokémon has the ability to freely control water.", "BUBBLE JET", PokeType.WATER, PokeType.NONE, new List<Ability> { Ability.WaterAbsorb, Ability.Hydration }, new Stats(130, 65, 60, 110, 95, 65), 1.0, 29.0, new GenderRatio(87.5, 12.5), "", null));
            Add(new Pokemon(135, "Jolteon", "Jolteon's cells generate a low level of electricity. This power is amplified by the static electricity of its fur,  enabling the Pokémon to drop thunderbolts. The bristling fur is made of electrically charged needles.", "LIGHTNING", PokeType.ELECTRIC, PokeType.NONE, new List<Ability> { Ability.VoltAbsorb, Ability.QuickFeet }, new Stats(65, 65, 60, 110, 95, 130), 0.8, 24.5, new GenderRatio(87.5, 12.5), "", null));
            Add(new Pokemon(136, "Flareon", "Flareon's fluffy fur has a functional purpose—it releases heat into the air so that its body does not get excessively hot. This Pokémon's body temperature can rise to a maximum of 1, 650 degrees Fahrenheit.", "FLAME", PokeType.FIRE, PokeType.NONE, new List<Ability> { Ability.FlashFire, Ability.Guts }, new Stats(65, 130, 60, 95, 110, 65), 0.9, 25.0, new GenderRatio(87.5, 12.5), "", null));
            Add(new Pokemon(137, "Porygon", "Porygon is capable of reverting itself entirely back to program data and entering cyberspace. This Pokémon is copy protected so it cannot be duplicated by copying.", "VIRTUAL", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.Trace, Ability.Download, Ability.Analytic }, new Stats(65, 60, 70, 85, 75, 40), 0.8, 36.5, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(138, "Omanyte", "Omanyte is one of the ancient and long-since-extinct Pokémon that have been regenerated from fossils by people. If attacked by an enemy,  it withdraws itself inside its hard shell.", "SPIRAL", PokeType.ROCK, PokeType.WATER, new List<Ability> { Ability.SwiftSwim, Ability.ShellArmor, Ability.WeakArmor }, new Stats(35, 40, 100, 90, 55, 35), 0.4, 7.5, new GenderRatio(87.5, 12.5), ("Omastar"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 40")));
            Add(new Pokemon(139, "Omastar", "Omastar uses its tentacles to capture its prey. It is believed to have become extinct because its shell grew too large and heavy,  causing its movements to become too slow and ponderous.", "SPIRAL", PokeType.ROCK, PokeType.WATER, new List<Ability> { Ability.SwiftSwim, Ability.ShellArmor, Ability.WeakArmor }, new Stats(70, 60, 125, 115, 70, 55), 1.0, 35.0, new GenderRatio(87.5, 12.5), "", null));
            Add(new Pokemon(140, "Kabuto", "Kabuto is a Pokémon that has been regenerated from a fossil. However,  in extremely rare cases,  living examples have been discovered. The Pokémon has not changed at all for 300 million years.", "SHELLFISH", PokeType.ROCK, PokeType.WATER, new List<Ability> { Ability.SwiftSwim, Ability.BattleArmor, Ability.WeakArmor }, new Stats(30, 80, 90, 55, 45, 55), 0.5, 11.5, new GenderRatio(87.5, 12.5), ("Kabutops"), new EvolveAction(EvolveTask.LEVEL_UP, "At level 40")));
            Add(new Pokemon(141, "Kabutops", "Kabutops swam underwater to hunt for its prey in ancient times. The Pokémon was apparently evolving from being a water dweller to living on land as evident from the beginnings of change in its gills and legs.", "SHELLFISH", PokeType.ROCK, PokeType.WATER, new List<Ability> { Ability.SwiftSwim, Ability.BattleArmor, Ability.WeakArmor }, new Stats(60, 115, 105, 65, 70, 80), 1.3, 40.5, new GenderRatio(87.5, 12.5), "", null));
            Add(new Pokemon(142, "Aerodactyl", "Aerodactyl is a Pokémon from the age of dinosaurs. It was regenerated from genetic material extracted from amber. It is imagined to have been the king of the skies in ancient times.", "FOSSIL", PokeType.ROCK, PokeType.FLYING, new List<Ability> { Ability.RockHead, Ability.Pressure, Ability.Unnerve }, new Stats(80, 105, 65, 60, 75, 130), 1.8, 59.0, new GenderRatio(87.5, 12.5), "", null));
            Add(new Pokemon(143, "Snorlax", "Snorlax's typical day consists of nothing more than eating and sleeping. It is such a docile Pokémon that there are children who use its expansive belly as a place to play.", "SLEEPING", PokeType.NORMAL, PokeType.NONE, new List<Ability> { Ability.Immunity, Ability.ThickFat, Ability.Gluttony }, new Stats(160, 110, 65, 65, 110, 30), 2.1, 1460.0, new GenderRatio(87.5, 12.5), "", null));
            Add(new Pokemon(144, "Articuno", "Articuno is a legendary bird Pokémon that can control ice. The flapping of its wings chills the air. As a result,  it is said that when this Pokémon flies,  snow will fall.", "FREEZE", PokeType.ICE, PokeType.FLYING, new List<Ability> { Ability.Pressure, Ability.SnowCloak }, new Stats(90, 85, 100, 95, 125, 85), 1.7, 55.4, null, "", null, true));
            Add(new Pokemon(145, "Zapdos", "Zapdos is a legendary bird Pokémon that has the ability to control electricity. It usually lives in thunderclouds. The Pokémon gains power if it is stricken by lightning bolts.", "ELECTRIC", PokeType.ELECTRIC, PokeType.FLYING, new List<Ability> { Ability.Pressure, Ability.Static }, new Stats(90, 90, 85, 125, 90, 100), 1.6, 52.6, null, "", null, true));
            Add(new Pokemon(146, "Moltres", "Moltres is a legendary bird Pokémon that has the ability to control fire. If this Pokémon is injured,  it is said to dip its body in the molten magma of a volcano to burn and heal itself.", "FLAME", PokeType.FIRE, PokeType.FLYING, new List<Ability> { Ability.Pressure, Ability.FlameBody }, new Stats(90, 100, 90, 125, 85, 90), 2.0, 60.0, null, "", null, true));
            Add(new Pokemon(147, "Dratini", "Dratini continually molts and sloughs off its old skin. It does so because the life energy within its body steadily builds to reach uncontrollable levels.", "DRAGON", PokeType.DRAGON, PokeType.NONE, new List<Ability> { Ability.ShedSkin, Ability.MarvelScale }, new Stats(41, 64, 45, 50, 50, 50), 1.8, 3.3, new GenderRatio(50.0, 50.0), ("Dragonair"), new EvolveAction(EvolveTask.LEVEL_UP, "At Level 30")));
            Add(new Pokemon(148, "Dragonair", "Dragonair stores an enormous amount of energy inside its body. It is said to alter weather conditions in its vicinity by discharging energy from the crystals on its neck and tail.", "DRAGON", PokeType.DRAGON, PokeType.NONE, new List<Ability> { Ability.ShedSkin, Ability.MarvelScale }, new Stats(61, 84, 65, 70, 70, 70), 4.0, 16.5, new GenderRatio(50.0, 50.0), ("Dragonite"), new EvolveAction(EvolveTask.LEVEL_UP, "At Level 55")));
            Add(new Pokemon(149, "Dragonite", "Dragonite is capable of circling the globe in just 16 hours. It is a kindhearted Pokémon that leads lost and foundering ships in a storm to the safety of land.", "DRAGON", PokeType.DRAGON, PokeType.FLYING, new List<Ability> { Ability.InnerFocus, Ability.Multiscale }, new Stats(91, 134, 95, 100, 100, 80), 2.2, 210.0, new GenderRatio(50.0, 50.0), "", null));
            Add(new Pokemon(150, "Mewtwo", "Mewtwo is a Pokémon that was created by genetic manipulation. However,  even though the scientific power of humans created this Pokémon's body,  they failed to endow Mewtwo with a compassionate heart.", "GENETIC", PokeType.PSYCHIC, PokeType.NONE, new List<Ability> { Ability.Pressure, Ability.Unnerve }, new Stats(106, 110, 90, 154, 90, 130), 2.0, 122.0, null, "", null, true));
            Add(new Pokemon(151, "Mew", "Mew is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will,  so it entirely avoids notice even if it approaches people.", "NEW SPECIES", PokeType.PSYCHIC, PokeType.NONE, new List<Ability> { Ability.Synchronize }, new Stats(100, 100, 100, 100, 100, 100), 0.4, 4.0, null, "", null, true));


            foreach (Pokemon pokemon in this)
            {
                if (this.Where(p => p.EvolveTo != null && p.EvolveTo.Name == pokemon.Name).Count() != 0)
                {
                    pokemon.EvolveFrom = this.Single(p => p.EvolveTo != null && p.EvolveTo.Name == pokemon.Name);
                    pokemon.EvolveFromAction = pokemon.EvolveFrom.EvolveToAction;
                    pokemon.EvolveFrom.EvolveTo = pokemon;
                }
                if (pokemon.EvolveToAction != null && pokemon.EvolveToAction.Task == EvolveTask.EEVEE_LUTION)
                {
                    pokemon.EvolveToAction = new EvolveAction(EvolveTask.EEVEE_LUTION);
                    GetPokemon("Vaporeon").EvolveFrom = pokemon;
                    GetPokemon("Vaporeon").EvolveFromAction = new EvolveAction(EvolveTask.USE_ITEM, "Water Stone");
                    GetPokemon("Jolteon").EvolveFrom = pokemon;
                    GetPokemon("Vaporeon").EvolveFromAction = new EvolveAction(EvolveTask.USE_ITEM, "Thunder Stone");
                    GetPokemon("Flareon").EvolveFrom = pokemon;
                    GetPokemon("Vaporeon").EvolveFromAction = new EvolveAction(EvolveTask.USE_ITEM, "Fire Stone");
                }
            }
        }
    }
}
